name: Bundle Size Check

on:
  pull_request:

jobs:
  bundle-size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install size-limit
        run: npm install --save-dev size-limit @size-limit/preset-app

      - name: Check bundle size
        run: npx size-limit