name: Lint & Type Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Run TypeScript
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npx eslint . --ext .js,.ts || true
