name: PR Summary with GPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.txt

      - name: Generate GPT-4.1 Summary
        id: gpt
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Calling GPT-4.1 to summarize diff..."
          SUMMARY=$(curl -s https://models.github.ai/inference/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
{
  "model": "openai/gpt-4.1",
  "messages": [
    { "role": "system", "content": "Summarize this GitHub PR code diff as a changelog-style bullet list." },
    { "role": "user", "content": "$(cat diff.txt | head -c 5000)" }
  ],
  "temperature": 0.7,
  "top_p": 1.0
}
EOF
          | jq -r '.choices[0].message.content')

          echo "$SUMMARY" > summary.txt
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment summary on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🧠 **GPT-4.1 Summary of Code Changes**
            ---
            ${{ steps.gpt.outputs.summary }}
