name: PR Summary with ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get PR Diff
        id: diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.txt

      - name: Summarize with OpenAI
        uses: dpz/diff-summarizer@v1
        with:
          openai_key: ${{ secrets.OPENAI_API_KEY }}
          diff_file: diff.txt
          model: gpt-4