name: PR Summary with GPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history so git diff works

      - name: Get PR diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.txt

      - name: Generate GPT-4.1 Summary
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cat <<EOF > payload.json
            {
              "model": "openai/gpt-4.1",
              "messages": [
                { "role": "system", "content": "Summarize this GitHub PR code diff as a changelog-style bullet list." },
                { "role": "user", "content": "$(cat diff.txt | head -c 5000)" }
              ],
              "temperature": 0.7,
              "top_p": 1.0
            }
            EOF

                      echo "Sending to GitHub AI inference..."
                      curl -s https://models.github.ai/inference/chat/completions \
                        -H "Authorization: Bearer $OPENAI_API_KEY" \
                        -H "Content-Type: application/json" \
                        -d @payload.json > response.json

                      cat response.json  # 👈 Print response for debugging

                      jq -r '.choices[0].message.content' response.json > summary.txt || echo "No summary generated"

      - name: Comment summary on PR
        if: success() && hashFiles('summary.txt') != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          COMMENT=$(cat summary.txt)

          gh pr comment "$PR_URL" \
            --body "🧠 **GPT-4.1 Summary of Code Changes**  
            ---  
            \`\`\`markdown  
            $COMMENT  
            \`\`\`"
       
